name: Build React to APK

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Update Browserslist DB (biar nggak warning)
      - name: Update Browserslist DB
        run: npx browserslist@latest --update-db

      # 5. Build React
      - name: Build React App
        run: npm run build

      # 6. Install Capacitor CLI
      - name: Install Capacitor
        run: npm install @capacitor/core @capacitor/cli --save

      # 7. Init Capacitor
      - name: Init Capacitor
        run: npx cap init react-attendance com.example.reactattendance --web-dir=build

      # 8. Add Android platform
      - name: Add Android platform
        run: npx cap add android

      # 9. Setup Java + Android SDK
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      # 10. Build APK
      - name: Build APK
        run: |
          cd android
          ./gradlew assembleDebug

      # 11. Upload APK
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: react-attendance-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
